# Nginx serveste DOAR fisierele statice.
# API-ul este apelat direct de browser pe portul 3000 (fara proxy).
server {
    listen 80;
    server_name _;

    location / {
        root  /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}